steps:
  - name: BuildAndPublish
    image: jekyll/jekyll
    when:
      - event: manual
      - event: push
    environment:
      CBTOKEN:
        from_secret: CI_CODEBERG_TOKEN
      CBMAIL:
        from_secret: CI_CODEBERG_COMMITER
    commands:
      - chmod -R a+w .
      - git config --global --add safe.directory /woodpecker/src/codeberg.org/iroco/iroco-blog/_site
      - git config --global user.email "$${CBMAIL}"
      - git config --global user.name "CI Builder"
      - git config --global init.defaultBranch pages
      - git clone -b pages https://codeberg.org/iroco/iroco-blog.git _site
      - chmod -R a+w _site
      - cd _site
      - git remote set-url origin https://$${CBTOKEN}@codeberg.org/iroco/iroco-blog.git
      - cd ..
      - bundle install
      - bundle exec jekyll build
      - cp domains _site/.domains
      - cd _site
      - git add --all
      - git commit -m "CI Jekyll Build done at $( env TZ=Europe/Paris date +"%Y-%m-%d %X %z %Z" ) [CI SKIP]"
      - git push
